### ISSUE TITLE
Not e10 compatible on mac?

### ISSUE THREAD

**Issue by Noitidart** [diegocr/GitHubExtIns#11]
I got a report from a user saying that when they clicked "add to firefox" from nightly it froze the browser then crashed. Other time they had to force quit. On mac. Using the nightly thats out as of today 12/6/14

**Comment by diegocr** [comment]
Nightly builds are...well, you know. Is this still an issue todays?

**Comment by Noitidart** [comment]
i dont know i last tested this back in december i dont have nightly :(
