### ISSUE TITLE
Noob here (sorry)

### ISSUE THREAD

**Issue by Baniita** [diegocr/GitHubExtIns#12]
I don't understand what it means by "extension files have to be in the root repository". Which is the root repository? Do I just paste the source in my profiles folder? I can't find any detailed instructions on this.

**Comment by Noitidart** [comment]
This video might help you understand: https://github.com/diegocr/GitHubExtIns/pull/10#issuecomment-64839334

**Comment by Noitidart** [comment]
I just watched the video, the first 36 seconds shows how to install it the normal way (the non pull request feature way)

**Comment by Baniita** [comment]
That... didn't quite match my question. ^ ^)" I'm sorry, I have no idea what xul files are, and there's no "add to firefox" button, because I haven't placed my "extension files in the root depository, and I have no idea how to do that.
The extension I want to install is here: https://github.com/anekos/Ank-Pixiv-Tool/tree/fix/does_not_work_in_firefox37/source
There's no xul file?

**Comment by Noitidart** [comment]
Works for me. Install the addon from AMO (addons.mozilla.org) then go to that link you gave me. Here's a screenshot of the "add to firefox" button:

![](http://i.imgur.com/bHp81B5.png)

**Comment by Baniita** [comment]
Oh.. I was looking in the wrong area... e _e)" Aha... Thanks. I'm assuming I didn't actually need to do anything else to make that button show up, then...
