### ISSUE TITLE
Doesn't work anymore (2015-04-17)

### ISSUE THREAD

**Issue by hurda** [diegocr/GitHubExtIns#14]
Firefox 37.0.1
GitHubExtIns 1.5.0
Example-repo: https://github.com/Infocatcher/Link_Properties_Plus/

install.rdf etc. is at the root, so the button should be displayed.

**Comment by Noitidart** [comment]
fix is found in this pull request: https://github.com/diegocr/GitHubExtIns/pull/10 so download and install from here: https://github.com/diegocr/GitHubExtIns/tree/3deb0311a3aeaee11fa3a77ddc58dbf84c3ae10c

**Comment by Noitidart** [comment]
I thought I posted a post here O_O did you see it ?

 I had said fix in PR: https://github.com/diegocr/GitHubExtIns/pull/10

**Comment by Noitidart** [comment]
Oh @diegocr did you just post that fix and delete my post? O_O

**Comment by diegocr** [comment]
What post? ;-)

In any case, you don't need to hijack every issue posted by users, it causes confusion.

**Comment by Noitidart** [comment]
I'm guessing your wink emote means yes you deleted my post especially with your use of such a dangerous word of "hijack"? Don't you mean "help"?

Kind of rude both of deleting my post and accusing me of "hijacking". I mean only the best I'm trying to help you (and especially the developers) out with such a great tool. I don't mean to offend you.

**Comment by diegocr** [comment]
Hmm, well... as you know English is not my native language, and the first word which came to my mind was "hijack" as used in forums when someone posts in a topic asking/mentioning something thinking "on his stuff"... I didn't meant to be rude, nor interpreted that as a dangerous word, just slang.

As i see it, pointing users to a PR here is confusing. The add-on at the moment doesn't work, so they can't just make use of it to upgrade the extension itself - That's just what i wanted to express, sorry if i did sound rude.

**Comment by Noitidart** [comment]
Thank you for that. I didn't know English is not your native language, you speak it better then me. I appreciate your follow up comment to clear that.

**Comment by hurda** [comment]
Thanks for the fast fix!
