### ISSUE TITLE
Not working on android - just gui issue

### ISSUE THREAD

**Issue by Noitidart** [diegocr/GitHubExtIns#17]
On Android it works but the button does not show, we have to click "request desktop page" then the button shows. This is because github has a different gui for mobile view. You can see this mobile version by spoofing your headers with this addon: https://addons.mozilla.org/en-US/firefox/addon/random-agent-spoofer/

Please hook up so it works on mobile site :)

**Comment by diegocr** [comment]
This is how it works:

1.- You have to tap the "View Code" button/link.
2.- Then in the file list page, tap the _options_ icon in the upper-right:

1.-![15490518644-75](https://cloud.githubusercontent.com/assets/734313/11609346/bc7c4e30-9b84-11e5-9c8b-4ac3de0b22f7.gif) 2.-![15490518459-75](https://cloud.githubusercontent.com/assets/734313/11609347/c8ce882e-9b84-11e5-8797-70578c819708.gif)

**Comment by Noitidart** [comment]
Ah sweet thanks @diegocr!!
