### ISSUE TITLE
Please update for design chaging of github.

### ISSUE THREAD

**Issue by kingtosh** [diegocr/GitHubExtIns#20]
After design changing, this add-on does'nt work.
Please update.

**Comment by Noitidart** [comment]
The design change didn't land yet did it?

Is it possible to access the new design somehow?

**Comment by jerone** [comment]
> Over the course of the next two weeks, we'll be rolling out the option to opt-in to the new design from any of your repositories with the click of a button.

https://github.com/blog/2085-a-new-look-for-repositories

**Comment by Martii** [comment]
It prompted me in a banner when I logged in a few hours ago to opt in... I haven't looked for the opt-out although it will probably become the default as mentioned in the blog. When logged out the sidebar is still present but when logged in, if opted in, it will show up top.

**Comment by KrasnayaPloshchad** [comment]
This problem is also appearing in #21
