### ISSUE TITLE
Cannot install add-on directly from GitHub in Firefox mobile

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [diegocr/GitHubExtIns#21]
Hi, 

I found your add-on cannot install add-on from GitHub directly in Firefox for Android when I opened this page:
https://github.com/jiacai2050/gooreplacer/tree/android

Please fix.

**Comment by Noitidart** [comment]
Yes its known limitation. You have to go to "menu" then "request desktop site" then it will work. This addon hasnt been hooked up for mobile version of website yet

**Comment by diegocr** [comment]
afaics, what you linked is an SDK addon, which is not yet supported -- see #9

**Comment by diegocr** [comment]
I've just tested 1.7a1 (currently in master, fixing #20) and it works fine in Nightly _(Mozilla Fennec 45.0a1 20151203053521 Android arm-eabi-gcc3)_
